Platform/Sophgo/SG2042_EVB_Board/SG2042.dsc
Silicon/Sophgo/SG2042Pkg/Library/PciHostBridgeLib/PciHostBridgeLib.inf
Silicon/Sophgo/SG2042Pkg/Library/PciHostBridgeLib/PciHostBridgeLibConstructor.c
Silicon/Sophgo/SG2042Pkg/SG2042Pkg.dec

Get the PCIe topology at the DXE phase by parsing devicetree, set the PcdMangoPcieEnableMask value dynamically.

Silicon/Sophgo: Get the PCIe topology at DXE phase

---

Silicon/Sophgo/SG2042Pkg/Sec/Memory.c

The physical memory range of 3GB to 4GB has been reserved for PCIe, so the real memory layout is segmented. To avoid relocation overflow occurring when GRUB2 boot kernel, we only initialized the lowest memory range, which is below 3GB.
The kernel will get the memory map from firmware by the UEFI Boot Service GetMemoryMap when executing efi_boot_kernel(). Although the device tree has been transferred to the kernel and is parsed, the real useable physical memory size is only in the range of 3GB.
Now we initialize the whole memory node from the device tree in the UEFI SEC phase. On condition that the GRUB2 had the corresponding temporary workaround to support the segmented memory layout for RISC-V.

Silicon/Sophgo: Initialize the whole memory node.

---

Silicon/Sophgo/SG2042Pkg/Drivers/MmcDxe/MmcIdentification.c

On Milk-V PioneerBox, SDHCI read data timeout always occurs which is caused by CRC error. Reduce the transfer frequency of the Micro SD card from 50MB to 25MB to keep the read and write right.

Silicon/Sophgo: Reduce the trans freq of SD card

---

Silicon/Sophgo/SG2042Pkg/Library/MmuLib/RiscVMmuLib.c

For the Pisces Server, the first memory node base address on CHIP1 is fixed at 512GB in the system map. SG2042 only supports Sv39, the high memory (512GB or more) is not allowed to create the memory map directly according to the MMU coding logic. So we do not create va-pa map for high memory at the EDKII phase.

Silicon/Sophgo: Not build high memory map for Sv39

---

Platform/Sophgo/SG2042_EVB_Board/SG2042.dsc

Disable CMO and Sstc features because they are not supported by the platform. And use SBI calls itself by default for Sophgo SG2042 platform.
Cc: dahogn <dahogn@hotmail.com>
Cc: meng-cz <mengcz1126@gmail.com>
Cc: USER0FISH <libing1202@outlook.com>
Reviewed-by: Sunil V L <sunilvl@ventanamicro.com>

Sophgo/SG2042Pkg: Disable CMO and Sstc features

---

Platform/Sophgo/SG2042_EVB_Board/SG2042.dsc
Platform/Sophgo/SG2042_EVB_Board/SG2042.fdf.inc

When FW_SIZE is 9MB, the linux 6.6 kernel boot process throws a memory access exception in the get_boot_config_from_initrd function. We have to modify FW_SIZE to 8MB (requires 2MB alignment) as a workaround.

Platform/Sophgo: Fix FW_SIZE to 8MB (requires 2MB alignment)

---

Silicon/Sophgo/SG2042Pkg/AcpiTables/Dsdt/Pci.asl

Set 'top-intc-id' and 'msix-supported' to 0 for PCI2 host bridge

Silicom/Sophgo/Acpi: Add attributes to PCI2

---

Silicon/Sophgo/Drivers/FlashFvbDxe/FlashFvbDxe.c
Silicon/Sophgo/Drivers/SpiDxe/SpiFlashMasterController.c
Silicon/Sophgo/Drivers/SpiDxe/SpiFlashMasterController.h

On the SG2260 platform, the SPIFMC includes an additional register 0x30 (OPT), for handling no address cmd transfer. To ensure read nor flash ID successfully, bit[1] must be set to disable no address cmd FIFO flush.

Silicon/Sophgo: Fix read nor flash ID failed

---

Platform/Sophgo/SG2380Pkg/SG2380.dsc
Platform/Sophgo/SG2380Pkg/SG2380.fdf
Platform/Sophgo/SG2380Pkg/SG2380.fdf.inc

- On the FPGA, Palladium emulation platform, or the SoC without SPI Nor Flash, we still use RamFvbServicesRuntimeDxe to keep the variables in RAM. FPGA_ENABLE is a compile option - "-D FPGA_ENABLE".
- Enlarge the size of the firmware region.

Platform/Sophgo: Add a compile option FPGA_ENABLE

---

Platform/Sophgo/SG2044Pkg/SG2044.dsc

When loading images into memory, the following error occurs:
MemoryProtectionCpuArchProtocolNotify:
ProtectUefiImageCommon - 0x8208B760
- 0x0000000082054000 - 0x000000000003C000 !!!!!!!!  Image Section Alignment(0x40) does not match Required Alignment (0x1000)  !!!!!!!! ProtectUefiImage failed to create image properties record
We set the linker's page size to 0x1000. Ensure that sections are aligned to the above page size when loaded into memory. i.e., SectionAlignment of the Optional Header of PE/COFF equals 4KB.

Platform/Sophgo: fix check RequiredAlignment error

---

Platform/Sophgo/SG2044Pkg/SG2044.dsc

- SG2044 supports Sstc extension.
- Set timer frequency to 50MHz.

Sophgo/SG2044Pkg: fix timer frequency

---

Platform/Sophgo/SG2380Pkg/SG2380.dsc

Sophgo/SG2380Pkg: fix timer frequency

---

Silicon/Sophgo/Drivers/SdHostDxe/SdHostDxe.c
Silicon/Sophgo/Drivers/SpiDxe/SpiFlashMasterController.c

Background:
1. Devices' base address on SG2042 are higher than 39bit (larger than 0x3FFFFFFFFF).
2. SG2042 uses T-HEAD C920v1 which only support Sv39, it doesn't support Sv48 and Sv57.
3. RISC-V MMU require 64:38 bits are the same, if bit38 is 1, then bit 64:39 should be 1.
When MMU is enabled, we cannot access device registers by physical address. We should make bit 64:39 1 when we want to access registers, otherwise, an page fault exception will occur.
Now, SG2044 and later chips always support Sv48, so remove these quirks of SG2042.

Sv39: Remove SG2042 Sv39 physical address quirk

---

Silicon/Sophgo/SG2044Pkg/Library/PciHostBridgeLib/PciHostBridgeLib.c
Silicon/Sophgo/SG2044Pkg/Library/PciPlatformLib/PciPlatformLib.c
Silicon/Sophgo/SG2044Pkg/Library/PciPlatformLib/PciPlatformLib.inf

After MMU enabled, all physical address should be mapped before using. For SG2044 PCIe controller, three regions should be mapped. DBI, ATU and a piece of config space. One should use gEfiCpuArchProtocolGuid service, SetMemoryAttributes function. This service won't add memory region to System Map. So if ACPI is used instead of device tree, we should add these memory regions to System Map, too.

SG2044: PCIe: Support MMU

---

Platform/Sophgo/SG2044Pkg/SG2044.dsc
Platform/Sophgo/SG2044Pkg/SG2044.fdf

1. SG2044 support MultiArchUefiPkg. Controlled by X64EMU_ENABLE.
2. Remove flash support. Flash driver not working if MMU is enabled. If flash driver is enabled, an page fault will generate.
3. SG2044 MMU enable Svpbmt
4. Set maximum MMU mode of SG2044 to Sv48

SG2044: MultiArchUefiPkg: Support MultiArchUefiPkg

---

Silicon/Sophgo/SG2044Pkg/Library/PciPlatformLib/PciPlatformLib.c

PCI_MAX_BUS, PCI_MAX_DEVICE and PCI_MAX_FUNC are 255, 31 and 7 respectively in EDK2. Not 256, 32 and 8. So we don't need minus these values by 1.

SG2044: Pci: Wrong BDF accessing config space

---

Silicon/Sophgo/SG2044Pkg/Library/PciPlatformLib/PciPlatformLib.c

Fixbug: Using device number as function number when config write

SG2044: PCIe: Wrong function number when cfg write

---

Silicon/Sophgo/SG2044Pkg/AcpiTables/Dsdt/Mmc.asl

- Close Device "MMC0" temporarily.
- Add "wp-inverted" property for Device "SDC0".
- Add "core-clk" property to support kernel get "SDC0" frequency base.

SG2044Pkg/AcpiTables: Modify Dsdt/Mmc.asl

---

Silicon/Sophgo/SG2044Pkg/AcpiTables/Dsdt/CommonDevices.asl

- Delete "_CCA" variable of Device "PWM0" because no dma engine.
- Add "base-clk" property to support kernel get "PWM0" frequency base.

SG2044Pkg/AcpiTables: Modify Dsdt/CommonDevices.asl

---

Silicon/Sophgo/Drivers/MmcDxe/MmcBlockIo.c
Silicon/Sophgo/Drivers/SdHostDxe/SdHci.c
Silicon/Sophgo/Drivers/SdHostDxe/SdHci.h
Silicon/Sophgo/Include/MmcHost.h

Exception occur when reading SD card.
Log as below:
!!!! RISCV64 Exception Type -
0000000000000001(EXCEPT_RISCV_INST_ACCESS_FAULT) !!!!
t0 = 0x00000000082AFF108        t1 = 0x00000000082AFF110
t2 = 0x000000000FFFFFFFF        t3 = 0x00000000000000000
t4 = 0x00000000000000400        t5 = 0x0000000000000002E
t6 = 0x00000000000000035        s0 = 0x00000000082AFF410
s1 = 0x00000000000000400        s2 = 0x00000000F773A6D00
s3 = 0x00000000000000001        s4 = 0x00000000F7F1CEC48
s5 = 0x00000000F7739D000        s6 = 0x000000000007AE000
s7 = 0x00000000000000400        s8 = 0x00000000F773A6D00
s9 = 0x00000000F7779E3F4       s10 = 0x00000000F777AD648
s11 = 0x00000000F773A8820        a0 = 0x00000000000000000
a1 = 0x0000000000000000D        a2 = 0x0FFFFFFFFAAAA0000
a3 = 0x0000000000000000D        a4 …

MmcDxe, SdHostDxe: Fixbug: Exception occur on SD

---

Platform/Sophgo/SG2044Pkg/SG2044.dsc
Silicon/Sophgo/Drivers/MmcDxe/MmcDebug.c
Silicon/Sophgo/SG2044Pkg/Library/PciHostBridgeLib/PciHostBridgeLib.c

eck2 commit: 8f048045934ea8ca390d843221fa954342132e6c removes the need of MDEPKG_NDEBUG

Sophgo: Remove debug macro MDEPKG_NDEBUG

---

Silicon/Sophgo/SG2044Pkg/Drivers/UiApp/FrontPage.c

Modify the issue where pressing "ESC" to exit the BIOS MENU results in a "Handle Not Found" error.

Modify exit the BIOS MENU results in a Handle Not Found error

---

Platform/Sophgo/SG2044Pkg/SG2044.dsc
Silicon/Sophgo/Library/Ds1307RealTimeClockLib/Ds1307RealTimeClockLib.c
Silicon/Sophgo/Library/Ds1307RealTimeClockLib/Ds1307RealTimeClockLib.inf
Silicon/Sophgo/Sophgo.dec

Use the Pcd variable to represent the i2c bus num used by RTC.
Signed-off-by: zhouwei.zhang <zhouwei.zhang@sophgo.com>

Ds1307RealTimeClockLib: Add Pcd variable

---

Platform/Sophgo/SG2044Pkg/SG2044.dsc
Platform/Sophgo/SG2044Pkg/SG2044.fdf
Silicon/Sophgo/Library/PlatformBootManagerLib/PlatformBm.c
Silicon/Sophgo/Library/PlatformBootManagerLib/PlatformBm.h
Silicon/Sophgo/Library/PlatformBootManagerLib/PlatformBootManagerLib.inf
Silicon/Sophgo/SG2044Pkg/Drivers/UiApp/FrontPageStrings.uni

Improve Hotkey Logic and Adjust BIOS MENU Page Design
1.Add deduplication logic to resolve the issue of duplicate Boot Options and enhance hotkey design. 
2.Revise the BIOS MENU VFR design.
Signed-off-by: lin peng <peng.lin@sophgo.com>

Improve Hotkey Logic and Adjust BIOS MENU Page Design

---

Silicon/Sophgo/SG2044Pkg/AcpiTables/Dsdt/Pci.asl
Silicon/Sophgo/SG2044Pkg/AcpiTables/Dsdt/SG2044EvbDsdt.asl

- "_CCA" means cache coherency attribute.
- Value 0: The device does not have hardware managed cache coherency which corresponds to the dma-noncoherent of the DTS.
- Value 1: The device has hardware managed cache coherency which corresponds to the dma-coherent of the DTS.
- Other Values: Reserved.

SG2044Pkg/AcpiTables: Correct the "_CCA" value of Dsdt/Pci.asl

---

Platform/Sophgo/SG2044Pkg/Drivers/SmbiosPlatformDxe/SmbiosPlatformDxe.h
Platform/Sophgo/SG2044Pkg/Drivers/SmbiosPlatformDxe/Type07/PlatformCacheFunction.c

- L3 cache size results in abnormal display whne the size exceeds UINT16

Modify SMBIOS Parsing from conf.ini to address an issue

---

Silicon/Sophgo/SG2044Pkg/AcpiTables/Dsdt/Pci.asl

SG2044 is PLIC based platforms, which means it doesn't support MSI natively. PCIe MSIs should routed to a dedicated MSI controller. This MSI controller wire interrupts to PLIC. So PCIe host need such MSI controller initialized before.
This commit delcares dependency between PCIe hosts and MSI controller. Linux kernel drivers of MSI controller should use acpi_dev_clear_dependencies to nofity ACPI probe framework that it has done. After which, ACPI probe continue with PCIe hosts.

SG2044/Dsdt: Add dependency between PCIe host and MSI controller

---

Platform/Sophgo/SG2044Pkg/SG2044.dsc
Platform/Sophgo/SG2044Pkg/SG2044.fdf.inc
Silicon/Sophgo/SG2044Pkg/AcpiTables/SG2044EvbAcpiTables.inf
Silicon/Sophgo/SG2044Pkg/AcpiTables/Spcr.aslc
Silicon/Sophgo/SG2044Pkg/Include/SG2044AcpiHeader.h
Silicon/Sophgo/Sophgo.dec

- Use format revision 4 of Spcr table.
- Get base, clock and baud of serial through pcd.

SG2044Pkg/AcpiTables: update Spcr table to support earlycon

---

Platform/Sophgo/SG2044Pkg/Drivers/SmbiosPlatformDxe/Type04/PlatformProcessorFunction.c
Platform/Sophgo/SG2044Pkg/Drivers/SmbiosPlatformDxe/Type07/PlatformCacheFunction.c
Platform/Sophgo/SG2044Pkg/Drivers/SmbiosPlatformDxe/Type17/PlatformMemoryDeviceFunction.c

- For CPU frequency in conf.ini, use the smallest unit and modify Type 04 to perform unit conversion.
- For cache size in conf.ini, use the smallest unit and modify Type 07 to perform unit conversion.
- For DDR data-rate in conf.ini, use the smallest unit and modify Type 17 to perform unit conversion.

Update the SMBIOS table population code based on the latest conf.ini

---

Silicon/Sophgo/SG2044Pkg/AcpiTables/Dsdt/Pci.asl

- RISC-V platforms need to use dependencies between PCI host bridge, Link devices and the interrupt controllers to ensure probe order. The dependency is like "Interrupt controller <-- Link Device <-- PCI Host bridge".
- If there is no dependency between Link device and PCI Host Bridge, then PCI devices may be probed prior to Link devices.  If a PCI device is probed before its Link device, we won't be able to find its INTx mapping.

SG2044Pkg/AcpiTables: update pci routing table and add "LINK_DEVICE"

---

Silicon/Sophgo/SG2044Pkg/AcpiTables/Rhct.aslc
Silicon/Sophgo/SG2044Pkg/Include/SG2044AcpiHeader.h

- ISA Node: ISA length use fixed value(256), and ISA string maximum number of characters is 254.
- Get ISA node length through "OFFSET_OF".

SG2044Pkg/AcpiTables: update Rhct.alsc

---

Silicon/Sophgo/SG2044Pkg/AcpiTables/Dsdt/Mmc.asl
Silicon/Sophgo/SG2044Pkg/AcpiTables/Dsdt/Uart.asl

- All devices are dma-noncoherent except PCIe. If the device does not describe _CCA, the default value in the kernel is "cca=1". However, for a device without a DMA engine, without "_CCA", the default dma coherent has no effect.
- Currently, in the APCI table, we only describe "_CCA" in SD, MMC and PCIe.

SG2044Pkg/AcpiTables: update "_CCA" value

---

Platform/Sophgo/SG2044Pkg/SG2044.dsc
Silicon/Sophgo/Drivers/Net/DwMac4SnpDxe/DwMac4DxeUtil.h
Silicon/Sophgo/Drivers/Net/DwMac4SnpDxe/DwMac4SnpDxe.c

- The `RecycledTxBuf` should be UINT64*
- Enable build ethernet driver by default

Sophgo/DwMac4SnpDxe: Fix the data length of `RecycledTxBuf`

---

Silicon/Sophgo/Library/ConfigUtilsLib/ConfigUtilsLib.c
Silicon/Sophgo/Library/ConfigUtilsLib/ConfigUtilsLib.inf

- ConfigUtilsLib.c: Add error handling to prevent boot hang when FLASH_ENABLE is FALSE, caused by attempting to read date and version from flash.
- ConfigUtilsLib.inf: Add dependencies for gSophgoSpiMasterProtocolGuid and gSophgoNorFlashProtocolGuid in the Depex section.

Library/ConfigUtilsLib/: Fix Flash Read Hang

---

Platform/Sophgo/SG2044Pkg/SG2044.dsc
Silicon/Sophgo/Include/Library/SmbiosInformationLib.h
Silicon/Sophgo/Library/SmbiosInformation/SmbiosInformationLib.c
Silicon/Sophgo/Library/SmbiosInformation/SmbiosInformationLib.inf
Silicon/Sophgo/SG2044Pkg/Drivers/Information/Information.c
Silicon/Sophgo/SG2044Pkg/Drivers/Information/Information.h
Silicon/Sophgo/SG2044Pkg/Drivers/Information/Information.inf
Silicon/Sophgo/SG2044Pkg/Drivers/Information/InformationNVDataStruc.h
Silicon/Sophgo/SG2044Pkg/Drivers/Information/InformationVfr.Vfr

- SmbiosInformation: Extract information from all SMBIOS tables, with the function interface name provided as ParseSmbiosTable.
- SG2044Pkg/Information: Remove the original logic for extracting information in Information, use SmbiosInformationLib, and modify the corresponding display logic.

SmbiosInformation: Add a library for retrieving information from SMBIOS.

---

Platform/Sophgo/SG2044Pkg/Drivers/SmbiosPlatformDxe/Type17/PlatformMemoryDeviceFunction.c
Silicon/Sophgo/Library/ConfigUtilsLib/ConfigUtilsLib.c

1.ConfigUtilsLib.c: Based on the corresponding eFuse cell,
check the values of the 2nd and 3rd bits to determine the current channel rank type,
and decide the DDR size of the current chip.
2.SmbiosPlatformDxe/Type17/PlatformMemoryDeviceFunction.c:Add logic to release the allocated memory
if reading from eFuse fails to avoid memory leaks.

Sophgo: Modify the logic to get DDR size from eFuse

---

Silicon/Sophgo/Include/Library/SmbiosInformationLib.h
Silicon/Sophgo/Library/SmbiosInformation/SmbiosInformationLib.c
Silicon/Sophgo/SG2044Pkg/Drivers/Information/Information.c

- AllocSmbiosData:Returns a pointer to the SMBIOS_PARSED_DATA structure type, which stores the parsed smbios information.
- FreeSmbiosData:The inverse function of the AllocSmbiosData function is used to release memory.

SmbiosInformationLib: Update library functions.

---

Silicon/Sophgo/SG2044Pkg/Drivers/BmcLanConfigDxe/BmcLanConfigNv.h
Silicon/Sophgo/SG2044Pkg/Drivers/Information/InformationNVDataStruc.h
Silicon/Sophgo/SG2044Pkg/Drivers/PasswordConfigDxe/PasswordConfigData.h
Silicon/Sophgo/SG2044Pkg/Drivers/PasswordConfigDxe/PasswordConfigFormGuid.h
Silicon/Sophgo/SG2044Pkg/Drivers/SetDateAndTime/SetDateAndTimeNv.h
Silicon/Sophgo/SG2044Pkg/Drivers/UiApp/FrontPage.c
Silicon/Sophgo/SG2044Pkg/Drivers/UiApp/FrontPage.h
Silicon/Sophgo/SG2044Pkg/Drivers/UiApp/FrontPageCustomizedUi.c
Silicon/Sophgo/SG2044Pkg/Drivers/UiApp/FrontPageNVDataStruc.h
Silicon/Sophgo/SG2044Pkg/Drivers/UiApp/FrontPageStrings.uni
Silicon/Sophgo/SG2044Pkg/Drivers/UiApp/FrontPageVfr.Vfr
Silicon/Sophgo/SG2044Pkg/Drivers/UiApp/UiApp.inf

- BmcLanConfigDxe/BmcLanConfigNv.h: Align BMC form ID with MENU settings.
- UiApp: Update MENU layout:
- Merge product information and serial port configuration into one screen.
- Merge time settings, password settings, and restore default settings into a single interface.
- Standardize Varstore structure to 4-byte alignment, including these files: InformationNVDataStruc.h; PasswordConfigData.h; SetDateAndTimeNv.h.

SG2044Pkg: Modify MENU layout and add BMC support

---

Silicon/Sophgo/Drivers/DwI2cDxe/DwI2cDxe.c

Resolve the issue where an redundant write 0 transfer is generated
during I2C communication with the slave device.
Signed-off-by: zhouwei.zhang <zhouwei.zhang@sophgo.com>

SG2044Pkg/DwI2cDxe: Fix redundant I2C transfer

---

Platform/Sophgo/SG2044Pkg/SG2044.dsc
Silicon/Sophgo/Library/Ds1307RealTimeClockLib/Ds1307RealTimeClockLib.c
Silicon/Sophgo/Library/Ds1307RealTimeClockLib/Ds1307RealTimeClockLib.inf
Silicon/Sophgo/Sophgo.dec

Use two Pcd variables to store I2C bus numbers used by RTC.
Signed-off-by: zhouwei.zhang <zhouwei.zhang@sophgo.com>

SG2044Pkg/Ds1307RealTimeClockLib: Add a RTC I2C bus

---

Silicon/Sophgo/SG2044Pkg/Drivers/BmcLanConfigDxe/BmcLanConfig.c
Silicon/Sophgo/SG2044Pkg/Drivers/IpmiBootDxe/IpmiBootDxe.c

- Updated debug messages in both IpmiBootEntry and BmcLanConfigEntry to clarify that a non-server board was detected and that server-specific initialization is being skipped.
- Changed the return value in both functions from an error code to EFI_SUCCESS when a non-server product is detected, indicating that the function completed successfully without attempting server-specific operations.

Sophgo: Update IpmiBootEntry() and BmcLanConfigEntry()

---

Silicon/Sophgo/SG2044Pkg/Drivers/UiApp/FrontPage.c
Silicon/Sophgo/SG2044Pkg/Drivers/UiApp/FrontPageNVDataStruc.h
Silicon/Sophgo/SG2044Pkg/Drivers/UiApp/FrontPageVfr.Vfr

- If booting from DTB is the default, do not display the ACPI disable control on the menu interface.

UiApp: Add new functionality for the ACPI disable control

---

Silicon/Sophgo/Library/ConfigUtilsLib/ConfigUtilsLib.c

- The issue of reading the efuse error in SMBIOS is caused by a problem with the logic of passing the size parameter in the code, which leads to incorrect returned values.

ConfigUtilsLib: Resolve the efuse reading error in SMBIOS.

---

Silicon/Sophgo/Drivers/Net/DwMac4SnpDxe/DwMac4DxeUtil.c
Silicon/Sophgo/Drivers/Net/DwMac4SnpDxe/DwMac4DxeUtil.h
Silicon/Sophgo/Drivers/Net/DwMac4SnpDxe/DwMac4SnpDxe.c
Silicon/Sophgo/Drivers/Net/MotorcommPhyDxe/Motorcomm8531PhyDxe.c

- change rx delay from 1.95ns to 2.10ns, which significantly reduce the amount of error data received
- increase rx/tx descriptor's ring buffer size to 256*2048
- disable unuse MAC config(jumbo), enable "Checksum offload"
- split ring buffer allocation into a single function
- remove unuse interrupt codes

 Improved packet loss problem (not completely solved)
